import { N8N_API_BASE_URL } from '../constants';
import { OrchestratorResponse, Project } from '../types';

// --- MOCK DATA FOR OFFLINE/FALLBACK MODE ---
const MOCK_PROJECT: Project = {
  id: 'offline-demo-project',
  name: 'Demo Session (Offline Mode)',
  status: 'active',
  created_at: new Date().toISOString()
};

const MOCK_DECISION: OrchestratorResponse = {
  decision: "APPROVED",
  overall_score: 94,
  principle_scores: {
    stewardship: 95, team: 90, stakeholders: 85, value: 98, systems_thinking: 80,
    leadership: 92, tailoring: 85, quality: 88, complexity: 75, risk: 70,
    adaptability: 85, change: 80
  },
  domain_analysis: {
    "Strategic Alignment": { score: 98, insight: "Strong alignment with business goals." },
    "Value Delivery": { score: 92, insight: "High ROI potential identified." }
  },
  action: "Proceed immediately. This is a simulated response because the n8n backend is unreachable. In a real scenario, this would be the strategic rationale generated by the AI.",
  conditions: [],
  next_steps: ["Allocate resources", "Schedule kickoff", "Define sprint goals"],
  risks: ["Backend availability (Simulated)", "Timeline compression"],
  estimated_impact: { "ROI": "150%", "Time_to_Market": "2 weeks" },
  monitoring_kpis: ["Cycle Time", "Lead Time", "Team Velocity"],
  success_criteria: ["Feature deployed to prod", "User satisfaction > 4.5"],
  execution_time_ms: 45,
  cost_usd: 0
};

/**
 * Crée ou récupère un projet "Session" pour l'utilisateur actuel.
 * Nécessaire car le workflow de décision n8n requiert un project_id.
 */
export const initializeProject = async (): Promise<Project> => {
  const storedProjectId = localStorage.getItem('nova_project_id');
  
  // Si on a déjà un ID, on essaie de le récupérer (vérif existence)
  if (storedProjectId) {
    try {
      const res = await fetch(`${N8N_API_BASE_URL}/projects/${storedProjectId}`);
      if (res.ok) {
        const json = await res.json();
        return json.data;
      }
    } catch (e) {
      console.warn("Impossible de récupérer le projet existant, création d'un nouveau.");
    }
  }

  // Création d'un nouveau projet par défaut
  try {
    const res = await fetch(`${N8N_API_BASE_URL}/projects`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: `Session ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
        description: "Projet de session temporaire créé par le frontend NovaProject",
        priority: "medium",
        owner: "Web User"
      })
    });

    if (!res.ok) throw new Error("Erreur lors de la création du projet n8n");
    
    const json = await res.json();
    const project = json.data;
    
    // Sauvegarde pour persistance
    localStorage.setItem('nova_project_id', project.id);
    return project;
  } catch (error) {
    console.warn("API Error (Project): Network unreachable. Switching to MOCK PROJECT.", error);
    // Return mock project to prevent app crash
    return MOCK_PROJECT;
  }
};

/**
 * Envoie une requête d'analyse au workflow de décision n8n.
 */
export const analyzeDecision = async (projectId: string, request: string): Promise<OrchestratorResponse> => {
  try {
    // If we are in mock mode (using the mock project ID), skip the network call
    if (projectId === MOCK_PROJECT.id) {
      await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate latency
      return MOCK_DECISION;
    }

    const res = await fetch(`${N8N_API_BASE_URL}/decision`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        project_id: projectId,
        request: request,
        request_type: 'general',
        user: 'web_user'
      })
    });

    if (!res.ok) {
      const errorText = await res.text();
      throw new Error(`Erreur API n8n (${res.status}): ${errorText}`);
    }

    const json = await res.json();
    
    // Le workflow n8n retourne l'objet inséré en base, qui contient 
    // le champ "pmbok_evaluation" avec la structure JSON complète de Claude.
    // On fusionne les métadonnées de l'exécution (temps, coût) avec l'évaluation.
    
    if (!json.pmbok_evaluation) {
      throw new Error("Format de réponse invalide: 'pmbok_evaluation' manquant");
    }

    return {
      ...json.pmbok_evaluation,
      execution_time_ms: json.execution_time_ms,
      cost_usd: json.cost_usd
    };

  } catch (error) {
    console.warn("API Error (Decision): Network unreachable. Switching to MOCK RESPONSE.", error);
    // Return mock response to allow UI testing/demo
    await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate latency
    return MOCK_DECISION;
  }
};
